"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase";

type DbStatus = "pending" | "ok" | "err";

const FEATURES = [
  {
    title: "Upload & parse",
    body: "Paste or upload a lab report; a rule-based parser extracts each marker, value, unit, reference range, and flag.",
  },
  {
    title: "Marker explainer",
    body: "Expand any marker for a calm, plain-language explanation of what it measures and whether it's worth raising with a clinician.",
  },
  {
    title: "Report summariser",
    body: "Generate a whole-report summary and a short, doctor-ready question list to bring to your appointment.",
  },
  {
    title: "Private by design",
    body: "Health data is special-category under UK GDPR. Row Level Security, encryption at rest, and strict retention windows apply.",
  },
];

export default function Home() {
  const [db, setDb] = useState<DbStatus>("pending");

  useEffect(() => {
    // Lightweight connectivity check against the public profiles table. RLS
    // returns zero rows for an anonymous visitor, which is the expected, healthy
    // result — we only care that the request reaches Supabase without erroring.
    const supabase = createClient();
    supabase
      .from("profiles")
      .select("id", { count: "exact", head: true })
      .then(({ error }) => setDb(error ? "err" : "ok"));
  }, []);

  return (
    <main>
      <span className="status">
        <span className={`dot ${db}`} />
        {db === "pending" && "Checking Supabase…"}
        {db === "ok" && "Connected to Supabase"}
        {db === "err" && "Supabase env vars not set"}
      </span>

      <h1>Lab Results Explainer</h1>
      <p className="lede">
        Understand what each marker on your lab report measures — in calm, plain
        language. Educational context, never a diagnosis.
      </p>

      <div className="disclaimer">
        This tool provides general educational information about lab markers. It
        does not diagnose conditions, recommend treatments, or replace clinical
        advice. Always discuss your results with a qualified clinician.
      </div>

      {FEATURES.map((f) => (
        <div className="card" key={f.title}>
          <h2>{f.title}</h2>
          <p>{f.body}</p>
        </div>
      ))}

      <footer>
        Generated by Lab Results Explainer for educational purposes only. Not a
        clinical document.
      </footer>
    </main>
  );
}
